### ISSUE TITLE
Changing Title Tag and Logo Not Reflected in App

### ISSUE THREAD

**Issue by arnabpal2022** [arnabpal2022/toDoList#5]
Currently, the title tag and logo of the app are not being updated correctly when attempting to change them. Users may want to customize the app's title and logo to match their branding or reflect the app's purpose accurately.

**Comment by arnabpal2022** [comment]
Fixed

**Comment by Sreyasree-001** [comment]
Can I work on this issue?

**Comment by arnabpal2022** [comment]
I've Assigned You.

**Comment by arnabpal2022** [comment]
#6 Issue Fixed.
Well Done @Sreyasree-001. Thanks For Contributing.
